/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cloud_logic_custom": [
        {
            "name": "vendorapi",
            "endpoint": "https://11s037yqr8.execute-api.us-east-1.amazonaws.com/test",
            "region": "us-east-1"
        }
    ],
    "aws_cognito_identity_pool_id": "us-east-1:c63e2594-9bbc-4878-a013-f7e1e40b21dc",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_qiR9iLEJG",
    "aws_user_pools_web_client_id": "5l8i9tlgt1604a3lagpktsjt80",
    "oauth": {},
    "aws_cognito_username_attributes": [
        "EMAIL"
    ],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ],
    "aws_user_files_s3_bucket": "amplify-vendorportal-test-225611-deployment",
    "aws_user_files_s3_bucket_region": "us-east-1"
};


export default awsmobile;
